version: '3.8'

services:
  redis-a:
    image: redis:latest
    container_name: redis-a
    ports:
      - "6379:6379"  # host port 6379 → redis-a

  redis-a-replica:
    image: redis:latest
    container_name: redis-a-replica
    depends_on:
      - redis-a
    command: ["redis-server", "--replicaof", "redis-a", "6379"]
    ports:
      - "6380:6379"  # host port 6380 → replica of redis-a

  redis-b:
    image: redis:latest
    container_name: redis-b
    ports:
      - "6381:6379"  # host port 6381 → redis-b

  redis-b-replica:
    image: redis:latest
    container_name: redis-b-replica
    depends_on:
      - redis-b
    command: ["redis-server", "--replicaof", "redis-b", "6379"]
    ports:
      - "6382:6379"  # host port 6382 → replica of redis-b
