version: '3.8'

services:
  servicea:
    build:
      context: .
      dockerfile: ServiceA/Dockerfile
    environment:
      - REDIS_SHARDS=shard-a:redis-a-replica:6379;shard-b:redis-b-replica:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 3s
      retries: 3
    deploy:
      replicas: 2

  serviceb:
    build:
      context: .
      dockerfile: ServiceB/Dockerfile
    environment:
      - REDIS_SHARDS=shard-a:redis-a:6379;shard-b:redis-b:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 3s
      retries: 3
    deploy:
      replicas: 2

  nginx:
    image: nginx:latest
    command: /bin/sh -c "sleep 5 && nginx -g 'daemon off;'"
    depends_on:
      servicea:
        condition: service_healthy
      serviceb:
        condition: service_healthy
    ports:
      - "8080:80"
      - "8443:443"
      - "9184:9184"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - nginx_cache:/tmp/nginx_cache
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  redis-a:
    image: redis:latest
    container_name: redis-a
  redis-a-replica:
    image: redis:latest
    container_name: redis-a-replica
    depends_on:
      - redis-a
    command: ["redis-server", "--replicaof", "redis-a", "6379"]

  redis-b:
    image: redis:latest
    container_name: redis-b
  redis-b-replica:
    image: redis:latest
    container_name: redis-b-replica
    depends_on:
      - redis-b
    command: ["redis-server", "--replicaof", "redis-b", "6379"]
    
volumes:
  nginx_cache: