version: '3.8'

services:
  servicea:
    build: ./ServiceA
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 3s
      retries: 3
    deploy:
      replicas: 2

  serviceb:
    build: ./ServiceB
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 3s
      retries: 3
    deploy:
      replicas: 2

  nginx:
    image: nginx:latest
    command: /bin/sh -c "sleep 5 && nginx -g 'daemon off;'"
    depends_on:
      servicea:
        condition: service_healthy
      serviceb:
        condition: service_healthy
    ports:
      - "8080:80"
      - "8443:443"
      - "9184:9184"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - nginx_cache:/tmp/nginx_cache
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
  redis-primary:
    image: redis:latest
    container_name: redis-primary
    ports:
      - "6379:6379" # optional can be removed if not testing locally
    command: ["redis-server"]
  redis-replica:
    image: redis:latest
    container_name: redis-replica
    depends_on:
      - redis-primary
    command: ["redis-server", "--replicaof", "redis-primary", "6379"]
volumes:
  nginx_cache: