version: '3.8'

services:
  servicea:
    build: ./ServiceA
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 2s
      retries: 5

  serviceb:
    build: ./ServiceB
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 2s
      retries: 5

  nginx:
    image: nginx:latest
    command: /bin/sh -c "sleep 5 && nginx -g 'daemon off;'"
    depends_on:
      servicea:
        condition: service_healthy
      serviceb:
        condition: service_healthy
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
